# Generated by Django 6.0 on 2025-12-20 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='キャビネット名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'キャビネット',
                'verbose_name_plural': 'キャビネット',
                'db_table': 'cabinets',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(db_index=True, max_length=5, unique=True, verbose_name='取引先コード')),
                ('client_name', models.CharField(max_length=200, verbose_name='取引先名')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '取引先',
                'verbose_name_plural': '取引先',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=5, unique=True, verbose_name='グループID')),
                ('name', models.CharField(max_length=200, verbose_name='グループ名')),
                ('client_code', models.CharField(db_index=True, max_length=5, verbose_name='取引先コード')),
                ('group_password', models.CharField(max_length=128, verbose_name='グループパスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('user_type', models.CharField(choices=[('admin', '管理者'), ('staff', 'スタッフ'), ('client', '取引先'), ('api', 'API')], max_length=20, verbose_name='ユーザー種別')),
                ('client_code', models.CharField(blank=True, db_index=True, max_length=5, null=True, verbose_name='取引先コード')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='氏名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフフラグ')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '利用者',
                'verbose_name_plural': '利用者',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='変更後取引先名')),
                ('address', models.TextField(blank=True, null=True, verbose_name='変更後住所')),
                ('group_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='変更後グループパスワード')),
                ('status', models.CharField(choices=[('pending', '未承認'), ('approved', '承認済み'), ('rejected', '却下')], db_index=True, default='pending', max_length=20, verbose_name='ステータス')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='却下理由')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='依頼日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_changes', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_changes', to=settings.AUTH_USER_MODEL, verbose_name='依頼者')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='documents.client', verbose_name='取引先')),
            ],
            options={
                'verbose_name': '変更依頼',
                'verbose_name_plural': '変更依頼',
                'db_table': 'change_requests',
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', '追加'), ('update', '更新'), ('delete', '削除')], max_length=20, verbose_name='操作種別')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者名')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='担当者メール')),
                ('contact_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='担当者パスワード')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_changes', to='documents.changerequest', verbose_name='変更依頼')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_changes', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': '変更依頼担当者',
                'verbose_name_plural': '変更依頼担当者',
                'db_table': 'change_request_contacts',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='フォルダ名')),
                ('folder_type', models.CharField(choices=[('root', 'ルート'), ('client', '取引先'), ('year', '年度'), ('month', '月')], max_length=20, verbose_name='フォルダ種別')),
                ('client_code', models.CharField(blank=True, db_index=True, max_length=5, null=True, verbose_name='取引先コード')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='年度')),
                ('month', models.CharField(blank=True, max_length=2, null=True, verbose_name='月')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='documents.cabinet', verbose_name='キャビネット')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder', verbose_name='親フォルダ')),
            ],
            options={
                'verbose_name': 'フォルダ',
                'verbose_name_plural': 'フォルダ',
                'db_table': 'folders',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, max_length=255, verbose_name='ファイル名')),
                ('document_type', models.CharField(choices=[('monthly', '月次請求書'), ('adhoc', '随時請求書')], max_length=20, verbose_name='文書種別')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='請求書番号')),
                ('invoice_date', models.DateField(verbose_name='請求日')),
                ('version', models.IntegerField(default=1, verbose_name='版数')),
                ('is_latest', models.BooleanField(db_index=True, default=True, verbose_name='最新版フラグ')),
                ('file_path', models.FileField(upload_to='documents/%Y/%m/', verbose_name='ファイルパス')),
                ('file_size', models.BigIntegerField(verbose_name='ファイルサイズ')),
                ('encrypt_flag', models.BooleanField(default=False, verbose_name='暗号化フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.folder', verbose_name='フォルダ')),
            ],
            options={
                'verbose_name': '文書',
                'verbose_name_plural': '文書',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read', '参照権限'), ('admin', '管理者権限')], max_length=20, verbose_name='権限種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.folder', verbose_name='フォルダ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='documents.group', verbose_name='グループ')),
            ],
            options={
                'verbose_name': 'フォルダ権限',
                'verbose_name_plural': 'フォルダ権限',
                'db_table': 'folder_permissions',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='documents.group', verbose_name='グループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': 'グループメンバー',
                'verbose_name_plural': 'グループメンバー',
                'db_table': 'group_members',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(db_index=True, max_length=5, verbose_name='取引先コード')),
                ('client_name', models.CharField(max_length=200, verbose_name='取引先名')),
                ('address', models.TextField(verbose_name='住所')),
                ('group_password', models.CharField(max_length=128, verbose_name='グループパスワード')),
                ('status', models.CharField(choices=[('pending', '未承認'), ('approved', '承認済み'), ('rejected', '却下')], db_index=True, default='pending', max_length=20, verbose_name='ステータス')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='却下理由')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='依頼日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
            ],
            options={
                'verbose_name': '新規登録依頼',
                'verbose_name_plural': '新規登録依頼',
                'db_table': 'registration_requests',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='担当者メール')),
                ('contact_password', models.CharField(max_length=128, verbose_name='担当者パスワード')),
                ('contact_order', models.IntegerField(default=1, verbose_name='順序')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='documents.registrationrequest', verbose_name='登録依頼')),
            ],
            options={
                'verbose_name': '新規登録依頼担当者',
                'verbose_name_plural': '新規登録依頼担当者',
                'db_table': 'registration_request_contacts',
                'ordering': ['contact_order'],
            },
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status'], name='change_requ_status_c1bccf_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['client_code'], name='folders_client__9d3600_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_name'], name='documents_file_na_a53640_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_latest'], name='documents_is_late_ccb748_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderpermission',
            unique_together={('folder', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['client_code'], name='registratio_client__e10183_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['status'], name='registratio_status_ac51a3_idx'),
        ),
    ]
