# Generated by Django 6.0 on 2025-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='ファイルデータ'),
        ),
    ]
